### ISSUE TITLE
Link error when building on ORNL Crusher (Frontier) with AMD Clang

### ISSUE THREAD

**Issue by kwryankrattiger** [mochi-hpc/mochi-margo#229]
When building mochi-margo in the E4S stack, incompatible flags seem to be passed for linking pthreads. This was worked around unsatisfactorily in Spack my forcefully adding the `-pthread` flag.

Details here.
https://github.com/spack/spack/pull/34414

**Comment by mdorier** [comment]
Can you share your environment file, compilers.yaml file, and packages.yaml file, so we can reproduce exactly the problem?

I have tested a few things this morning:
- On Linux with gcc, both `-pthread` and `-lpthread` appear to be added;
- Same with clang on Linux
- Same with apple-clang on Mac

I tried on Crusher but I don't see a `clang@14.0.0-rocm5.2.0` compiler detected, even when loading PrgEnv-amd. I see a `clang@14.0.2` but I wasn't able to build anything with it. Spack also found a `rocmcc@5.1.0` compiler and building mochi-margo with it works fine.

@carns can you follow up on this next week, as I won't be available?

**Comment by carns** [comment]
I can definitely follow up, and I'm happy to try to repro on crusher if we can get a spack configuration to trigger it.

Just pasting here for reference so I don't forget the config, but I've added lines like this in a spack env yaml before to make the mochi-margo@main point to a local source directory.  This should make it reasonably straightforward to experiment with autoconf macro changes, even if problems only show up within the context of a spack build.

```
  develop:
    mochi-margo:
      spec: mochi-margo@main
      path: /home/carns/working/src/mochi/mochi-margo
```

**Comment by kwryankrattiger** [comment]
Here are the facility configs that we are using on crusher.

https://github.com/E4S-Project/facility-external-spack-configs/tree/master/crusher

You will need to add this to the append_path section for the rocm compiler:

```yaml
append_path:
  PKG_CONFIG_PATH: /opt/cray/xpmem/2.4.4-2.3_11.2__gff0e1d9.shasta/lib64/pkgconfig
```

The environement is 

```yaml
spack:
  packages:
    all:
      require: '%clang@14.0.0-rocm5.2.0'
      compiler: [clang@14.0.0-rocm5.2.0]
  specs: [ecp-data-vis-sdk +unifyfs]
  view: false
  concretizer:
    unify: false
  upstreams:
    e4s-22-11:
      install_tree: /gpfs/alpine/csc439/world-shared/E4S/ParaTools/22.11/PrgEnv-amd/spack/opt/spack/
```

**Comment by mdorier** [comment]
I gave this a try:
```
module load PrgEnv-amd
module load amd/5.2.0
spack compiler find # this makes it find rocmcc@5.2.0, which is what's named "clang@14.0.0-rocm5.2.0" in the above crusher config
spack install mochi-margo%rocmcc@5.2.0^mercury~boostsys
```
And it builds fine, so a couple of things could be happening:
- Either a difference in the extra modules loaded or flags added to the config change something
- Or building `ecp-data-vis-sdk +unifyfs` introduces packages that change the flags (I don't know how)

**Comment by eugeneswalker** [comment]
> I gave this a try:
> 
> ```
> module load PrgEnv-amd
> module load amd/5.2.0
> spack compiler find # this makes it find rocmcc@5.2.0, which is what's named "clang@14.0.0-rocm5.2.0" in the above crusher config
> spack install mochi-margo%rocmcc@5.2.0^mercury~boostsys
> ```
> 
> And it builds fine, so a couple of things could be happening:
> 
>     * Either a difference in the extra modules loaded or flags added to the config change something
> 
>     * Or building `ecp-data-vis-sdk +unifyfs` introduces packages that change the flags (I don't know how)

`spack compiler find` entries for `rocmcc` looks like it doesn't use the Cray wrappers `cc/CC/ftn` -- can you try please try using this as the compiler definition:

```
  compilers:
  - compiler:
      spec: clang@14.0.0-rocm5.2.0
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-amd/8.3.3
      - amd/5.2.0
      - xpmem
      - craype-x86-trento
      - libfabric
      - cray-pmi/6.1.3
      environment:
        set:
          RFE_811452_DISABLE: '1'
        append_path:
          PKG_CONFIG_PATH: /opt/cray/xpmem/2.4.4-2.3_11.2__gff0e1d9.shasta/lib64/pkgconfig
          LD_LIBRARY_PATH: /opt/cray/pe/gcc-libs:/opt/cray/libfabric/1.15.0.0/lib64
        prepend_path:
          LD_LIBRARY_PATH: /opt/cray/pe/pmi/6.1.3/lib
          LIBRARY_PATH: /opt/rocm-5.2.0/lib:/opt/rocm-5.2.0/lib64
      extra_rpaths:
      - /opt/rocm-5.2.0/lib
      - /opt/rocm-5.2.0/lib64
      - /opt/cray/pe/gcc-libs
      - /opt/cray/gcc-libs
```

This is what we use to build all 500+ other packages and this has worked well for us.
